### ISSUE TITLE
Error in req_perform(useast) : Failed to perform HTTP request.

### ISSUE THREAD

**Issue by satish1907** [grimbough/biomaRt#105]
Possible SSL connectivity problems detected.
Please report this issue at https://github.com/grimbough/biomaRt/issues
Error in req_perform(useast) : Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.

        biomart                version
1         genes      Ensembl Genes 112
2 mouse_strains      Mouse strains 112
3          snps  Ensembl Variation 112
4    regulation Ensembl Regulation 112

**Comment by satish1907** [comment]
Resolved now

**Comment by splaisan** [comment]
Hi!
not resolved for me:

ubuntu 22 (uptodate)
R 4.4.0
RStudio server 2023.12.1 Build 402
biomaRt 2.60.0

```
> ensembl <- useEnsembl(biomart = "genes")
Possible SSL connectivity problems detected.
Please report this issue at https://github.com/grimbough/biomaRt/issues
Error in req_perform(useast) : Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! SSL peer certificate or SSH remote key was not OK: [useast.ensembl.org] SSL certificate problem: certificate has expired
```

**Comment by splaisan** [comment]
apparently, I had an older version of fastmap (1.1.1) that was not high enough but not triggering a warning with BiocManager::valid().

This fixed my issue after installing fastmap 1.2.0

```
remove.packages("fastmap")
BiocManager::install("fastmap")
```

**Comment by grimbough** [comment]
I think the original issue reported here was an SSL certificate issue that was resolved by the Ensembl team.

I'm not clear why updating `fastmap` would have any effect on this, as I don't think there's any link between it and `biomaRt`, but I'm glad the issue is resolved.
